[package]
name = "HotKeyManager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
windows = { version = "0.58.0", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Diagnostics_ToolHelp",
] }
windows-hotkeys = "0.2.1"
